version: '3.3'

services:
    db:
        image: mysql:latest
        ports:
            - '3306:3306'
        environment:
            MYSQL_USER: "${DB_USERNAME}"
            MYSQL_PASSWORD: "${DB_PASSWORD}"
            MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
            MYSQL_DB: "${DB_DATABASE}"
        restart: always
