version: '3.3'

services:
    postgres:
        image: postgres:14.5
        ports:
            - '5432:5432'
        environment:
            POSTGRES_USER: "${RDS_USERNAME}"
            POSTGRES_PASSWORD: "${RDS_PASSWORD}"
            POSTGRES_DB: "${RDS_DATABASE}"
        restart: always
